const ONBOARDING_EMAIL = "EMAIL";
const ONBOARDING_PASSWORD = "PASSWORD";
const ONBOARDING_ADDRESS = "ADDRESS";

enum OnboardingStep {
  ONBOARDING_EMAIL,
  ONBOARDING_PASSWORD,
  ONBOARDING_ADDRESS
}
